### ISSUE TITLE
preprocessing for galaxy sdss.

### ISSUE THREAD

**Issue by amirrezadolatpour2000** [POFK/starspectraclassifier#1]
Hello,
In my project, I need to preprocess galaxy spectra. I would like to know if your existing preprocessing steps are sufficient for galaxy spectra, or if there are additional considerations or modifications I need to make to ensure accurate preprocessing.

**Comment by POFK** [comment]
Hi, @amirrezadolatpour2000  Whether additional considerations or modifications are needed depends on your purpose.

This project is designed and used to classify star spectra, which is one step in my work many years ago. Galaxy spectra are different from stars, and your data may have its own issues that need attention. 

Your data preprocessing should amplify the information you care about and eliminate as much noise as possible.

Finally, please note that this is a very old Python project (although it was only 5 years ago, it feels like a century for Python and AI). There may be many trivial issues that need to be solved when deploying, such as python=2.7...
